// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type Metadatum struct {
	Version       string
	AssetsPath    string
	TemplatesPath string
}

type User struct {
	ID             int64
	Handle         string
	HashedPassword string
	Clan           string
	Magic          string
	Enabled        string
}
